version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css
- url: /fonts
  static_dir: static/fonts
- url: /js
  static_dir: static/js
- url: /img
  static_dir: static/img
- url: /.*
  script: code.app
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: lxml
  version: latest

builtins:
- deferred: on
- appstats: on

